import './globals.css'
import HeaderMobile from "@/app/components/HeaderMobile";
import Footer from "@/app/components/Footer";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="2xl:mx-60 mt-4 bg-neutral-200 font-montserrat">
      <HeaderMobile/>
      {children}
      <Footer/></body>
    </html>
  )
}
